# ============================================
# AI Hallucination Detector - LLM Module
# ============================================

import random
import time
import re

# Optional: Uncomment if using OpenAI API
# from openai import OpenAI
# client = OpenAI(api_key="YOUR_API_KEY")

# ============================================
# 1. RESPONSE CLEANING
# ============================================

def clean_response(text):
    text = text.strip()
    text = re.sub(r'\s+', ' ', text)
    return text


# ============================================
# 2. SIMPLE RULE-BASED RESPONSES
# ============================================

def rule_based_response(query):
    query = query.lower()

    if "who is narendra modi" in query:
        return "Narendra Modi is the Prime Minister of India."

    if "capital of india" in query:
        return "The capital of India is New Delhi."

    if "who is virat kohli" in query:
        return "Virat Kohli is an Indian international cricketer."

    if "what is python" in query:
        return "Python is a high-level programming language."

    return None


# ============================================
# 3. PROGRAMMING RESPONSE GENERATOR
# ============================================

def generate_programming_response(query):

    if "marks" in query and "program" in query:
        return """
def calculate_results(marks):
    total = sum(marks)
    avg = total / len(marks)
    percentage = (total / (len(marks) * 100)) * 100

    if percentage >= 90:
        grade = 'A'
    elif percentage >= 75:
        grade = 'B'
    elif percentage >= 60:
        grade = 'C'
    else:
        grade = 'D'

    return total, avg, percentage, grade


marks = []
for i in range(5):
    m = int(input(f"Enter marks for subject {i+1}: "))
    marks.append(m)

total, avg, per, grade = calculate_results(marks)

print("Total:", total)
print("Average:", avg)
print("Percentage:", per)
print("Grade:", grade)
        """

    if "addition" in query:
        return """
a = int(input("Enter a: "))
b = int(input("Enter b: "))
print("Sum:", a + b)
        """

    return None


# ============================================
# 4. SIMULATED LLM RESPONSE
# ============================================

def simulated_llm_response(query):
    responses = [
        "This is a generated AI response based on the query.",
        "The answer depends on the context provided.",
        "This is an approximate answer generated by AI."
    ]
    return random.choice(responses)


# ============================================
# 5. OPTIONAL OPENAI API RESPONSE
# ============================================

def openai_response(query):
    try:
        # Uncomment below if API is enabled

        """
        response = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[
                {"role": "system", "content": "You are a helpful AI assistant."},
                {"role": "user", "content": query}
            ],
            temperature=0.7
        )

        return response.choices[0].message.content
        """
        return None

    except Exception as e:
        print("API Error:", e)
        return None


# ============================================
# 6. QUERY CLASSIFIER
# ============================================

def classify_query(query):
    query = query.lower()

    if "program" in query or "python" in query:
        return "programming"

    if "who is" in query or "what is" in query:
        return "factual"

    return "general"


# ============================================
# 7. RESPONSE GENERATOR PIPELINE
# ============================================

def generate_response(query):

    query_type = classify_query(query)

    print("LLM DEBUG TYPE:", query_type)

    # Step 1: Rule-based
    response = rule_based_response(query)
    if response:
        return clean_response(response), "rule-based"

    # Step 2: Programming
    if query_type == "programming":
        response = generate_programming_response(query)
        if response:
            return clean_response(response), "programmed"

    # Step 3: OpenAI API
    response = openai_response(query)
    if response:
        return clean_response(response), "openai"

    # Step 4: Fallback simulated
    response = simulated_llm_response(query)
    return clean_response(response), "simulated"


# ============================================
# 8. CONFIDENCE SCORING
# ============================================

def confidence_score(source):

    if source == "rule-based":
        return 0.9

    if source == "programmed":
        return 0.95

    if source == "openai":
        return 0.85

    return 0.5


# ============================================
# 9. RESPONSE PACKAGER
# ============================================

def get_ai_response(query):

    start_time = time.time()

    response, source = generate_response(query)
    confidence = confidence_score(source)

    end_time = time.time()
    latency = round(end_time - start_time, 3)

    return {
        "query": query,
        "response": response,
        "source": source,
        "confidence": confidence,
        "latency": latency
    }


# ============================================
# 10. RESPONSE FORMATTER
# ============================================

def format_response(result):

    return f"""
Query: {result['query']}

Response:
{result['response']}

Source: {result['source']}
Confidence: {result['confidence']}
Latency: {result['latency']} sec
"""


# ============================================
# 11. TEST BLOCK
# ============================================

if __name__ == "__main__":

    while True:
        query = input("\nEnter your question (or 'exit'): ")

        if query.lower() == "exit":
            break

        result = get_ai_response(query)

        print("\n===== AI RESPONSE =====")
        print(format_response(result))